# Gradle
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
javaVersion=21
# Mod
modId=create_cyber_goggles
modName=Create Goggles forked
modDisplayName=Create: Cyber Goggles
modLicense=MIT
modVersion=8.5.3
modGroupId=io.github.forgestove
modAuthors=ForgeStove, forked by krispyking24
modCredits=CMS, misterpemodder, Alex Guha, catboybinary
modDisplayUrl=https://github.com/krispyking24/CreateCyberGoggles
modIssueUrl=https://github.com/krispyking24/CreateCyberGoggles/issues
modDescription=A client-side mod for Create that provides modular assistance features.
# Version
mcVersion=1.21.1
# https://maven.neoforged.net/releases/net/neoforged/neoforge/maven-metadata.xml
loaderVersion=21.1.248
parchmentVersion=2024.11.17
createMinVersion=6.0.10
# https://maven.createmod.net:6085/com/simibubi/create/create-1.21.1/maven-metadata.xml
createVersion=6.0.11-300
# https://maven.createmod.net:6085/net/createmod/ponder/ponder-neoforge/maven-metadata.xml
ponderVersion=1.0.87
# https://maven.createmod.net:6085/dev/engine-room/flywheel/flywheel-neoforge-1.21.1/maven-metadata.xml
flywheelVersion=1.0.6-44
# https://mvn.devos.one/snapshots/com/tterrag/registrate/Registrate/maven-metadata.xml
registrateVersion=MC1.21-1.3.0+67
# https://maven.ryanhcode.dev/releases/dev/eriksonn/aeronautics/aeronautics-neoforge-1.21.1/maven-metadata.xml
areoVersion=1.3.1
# https://maven.ryanhcode.dev/releases/dev/ryanhcode/sable/sable-neoforge-1.21.1/maven-metadata.xml
sableVersion=2.0.5
# https://maven.ryanhcode.dev/releases/dev/ryanhcode/sable-companion/sable-companion-common-1.21.1/maven-metadata.xml
sableCompanionVersion=1.6.0
# https://maven.blamejared.com/foundry/veil/veil-neoforge-1.21.1/maven-metadata.xml
veilVersion=4.4.1
# https://maven.blamejared.com/mezz/jei/jei-1.21.1-neoforge/maven-metadata.xml
jeiVersion=19.27.0.350
# https://modrinth.com/mod/emi/versions?g=1.21.1&l=neoforge
emiVersion=1.1.24
# https://modrinth.com/mod/jade/versions?g=1.21.1&l=neoforge
jadeVersion=15.10.6
# https://modrinth.com/mod/create-enchantment-industry/versions?g=1.21.1&l=neoforge
ceiVersion=2.5.3
# https://modrinth.com/mod/create-dragons-plus/versions?g=1.21.1&l=neoforge
dragonPlusVersion=1.11.7b
# https://modrinth.com/mod/createfluidlogistic/versions?g=1.21.1&l=neoforge
fluidlogisticVersion=wxemWsQ2
sophisticatedCoreVersion=1.4.82.2230
# https://maven.blamejared.com/com/hollingsworth/ars_nouveau/ars_nouveau-1.21.1/maven-metadata.xml
arsNouveauVersion=5.13.1.1400
# https://modrinth.com/mod/ae2/versions?g=1.21.1&l=neoforge
appliedenergisticsVersion=19.2.17
# https://modrinth.com/mod/thirst-was-reclaimed/versions?g=1.21.1&l=neoforge
thirstVersion=3.0.4
mixinAgentVersion=1.1
# Loader
loader=neoforge
loaderCap=NeoForge
