modLoader = "javafml"
loaderVersion = "0"
issueTrackerURL = "${modIssueUrl}"
license = "${modLicense}"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modDisplayName}"
authors = "${modAuthors}"
credits = "${modCredits}"
displayURL = "${modDisplayUrl}"
description = '''${modDescription}'''
logoFile = "icon.png"
logoBlur = false

[[mixins]]
config = "${modId}.mixins.json"

[[dependencies."${modId}"]]
modId = "neoforge"
type = "required"
ordering = "NONE"
side = "BOTH"

[[dependencies."${modId}"]]
modId = "minecraft"
type = "required"
ordering = "NONE"
side = "BOTH"

[[dependencies."${modId}"]]
modId = "create"
type = "required"
ordering = "NONE"
side = "BOTH"
